language: node_js
node_js:
  - "6.11"
sudo: required
services:
  - mongodb
  - redis-server
  - docker
cache:
  directories:
  - node_modules
git:
  depth: 3
stages:
  - test
  - name: docker
    if: (branch = develop AND type = push) OR (branch = ci-build)
jobs:
  include:
    - stage: test
      script:
        - npm run test
    - stage: docker
      script: 
        - ./devops/build-api.sh
        - cd devops; ./build-mongodb.sh
