language: node_js
node_js:
  - "6.11"
sudo: required
services:
  - mongodb
  - redis-server
  - docker
cache:
  directories:
  - node_modules
git:
  depth: 3
script:
  # - yarn test:check-coverage
  #- npm run test
  - ./devops/build-ci.sh
after_script:
  # - yarn report-coverage
